server:
  port: 8080
spring:
  application:
    name: "ms-auth-service"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: "${R2DBC_HOST}"
    port: "${R2DBC_PORT}"
    database: "${R2DBC_DATABASE}"
    username: "${R2DBC_USERNAME}"
    password: "${R2DBC_PASSWORD}"

security:
  jwt:
    secret: "${JWT_SECRET}"
    ttl-seconds: "${JWT_EXPIRATION}"

routes:
  auth-api-path: "/api/v1/auth/login"
  user-api-path: "/api/v1/usuarios"